version: '3.8'
services:
  codeweb:
    build: .
    container_name: codeweb_app
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - ./temp:/app/temp
      - ./dist:/app/dist