version: '3.8'
services:
  codeweb:
    build: .
    container_name: codeweb_app
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=/CodeWEB/
    # Giữ lại volume này nếu bạn muốn thư mục temp được đồng bộ ra ngoài
    # volumes:
    #   - ./temp:/app/temp